### ISSUE TITLE
ReferenceError: util is not defined

### ISSUE THREAD

**Issue by zheoreh** [Download/ulog#4]
[0] /home/neo/projects/dm-iwish/node_modules/ulog/node.js:12
[0] 			logger = function(){stream.write(util.format.apply(this, arguments) + '\n')}
[0] 			                                 ^
[0] 
[0] ReferenceError: util is not defined
[0]     at Object.logger (/home/neo/projects/dm-iwish/node_modules/ulog/node.js:12:37)
[0]     at Object.<anonymous> (/home/neo/projects/dm-iwish/node_modules/just-wait/bin/just-wait.js:64:6)
[0]     at Module._compile (module.js:556:32)
[0]     at Object.Module._extensions..js (module.js:565:10)
[0]     at Module.load (module.js:473:32)
[0]     at tryModuleLoad (module.js:432:12)
[0]     at Function.Module._load (module.js:424:3)
[0]     at Module.require (module.js:483:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/home/neo/projects/dm-iwish/node_modules/just-wait/index.js:1:63)
[0] npm run watch-server-start exited with code 1

**Comment by zheoreh** [comment]
@Download Can you resolve it sooner. I use just-wait module and it uses your module. Thanks.

**Comment by Download** [comment]
I will have a look! Thanks for reporting it.

**Comment by Download** [comment]
@zheoreh 
Can you please get the new version of node.js and replace the file
`/home/neo/projects/dm-iwish/node_modules/ulog/node.js`
with the new version and see if that resolves it?

If so, I will promptly create a new version of both ulog and just-wait and publish them to NPM.

**Comment by zheoreh** [comment]
@Download I am sure it will be work)
But I tested and it works.
I wait for a new version of ulog module in NPM.
Thanks.

**Comment by Download** [comment]
@zheoreh ulog 1.0.2 is on NPM. I will also create a new versio of just-wait and publish that as well.

Feel free to re-open if you still have issues.

**Comment by zheoreh** [comment]
Thanks. It works fine now.
